### ISSUE TITLE
Oportunidades de Mejora

### ISSUE THREAD

**Issue by enelramon** [Adrielv/proyectoFinal#1]
1. El nombre del Proyecto y el repositorio deben indicar algo mas parecido a su proyecto final. (**Algo como el nombre del sistema**)

**2. ****DAL**

2.1. Recuerda que el nombre de la base de datos debería asemejarse al nombre del sistema.

2.2. No pusiste el script de la base de datos en el proyecto. (favor agregar)

3. **ENTIDADES**

3.1. Debes revisar los nombres de los campos ya que no están acorde con los nombres que indique en la tarea.

4. **UI**

4.1. El formulario principal no debe llamarse Form1.

4.2. El registro de usuarios debes llamarlo **rUsuarios.**

4.3. El Botón Editar no va.

4.4. Si presiona doble clic sobre un objeto sin querer debes recordar remover el método que se genera.

private void EmailmaskedTextBox_TextChanged(object sender, EventArgs e)

**Comment by Adrielv** [comment]
Profesor tuve un problemita para volver a subirlo a este mismo repositorio los cambios, lo que hice fue hacer uno nuevo espero que eso no sea problema https://github.com/Adrielv/VillarSolucions.git
